### PR TITLE
[WIP] Support for reading device information

### PR DESCRIPTION
**Pull request by ScholliYT**
This PR will add featues for reading device information like `model number`, `version number` and `id` from the sensor (As requested by the issue #15). 

See the [datasheet](https://cdn-shop.adafruit.com/datasheets/AM2315.pdf) (page 17) for reference. 

New methods in this PR:

``` c
uint16_t readModelNumber();
uint8_t  readVersionNumber();
uint32_t readID();
```

⚠️ I didn't test this feature until now. You might wanna wait for that before merging.

### CODE REVIEW

**Comment by ScholliYT** [comment]
After testing this code for a bit, it seems like these 3 registers are always empty (everyting 0). At least for the two sensor I tested with @ladyada

**Comment by ladyada** [comment]
could be - this sensor is not very well documented :(

**Comment by caternuson** [comment]
Closing this PR. Looks like it maybe did not work? Also, it would need to be reworked using BusIO calls.

**Comment by caternuson** [comment]
FWIW - I just did a quick rough in for this and also got back all `0`s from those register. So...yah... :shrug:

**Pull request closed without merging**
